name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: npm install and test run
        run: |
          npm install
          npm report || true

      - name: npm run coverage
        run: npm run coverage || true

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2.2.3

      - name: Upload Mocha Awesome test report
        uses: actions/upload-artifact@v4
        with:
          name: mocha-awesome-report
          path: mochawesome-report/